export const SHOP_TYPES = [
  { value: 'ELECTRONICS', label: 'Eletrônicos' },
  { value: 'FASHION', label: 'Moda' },
  { value: 'SERVICES', label: 'Serviços' },
  { value: 'REAL_ESTATE_FURNITURE', label: 'Imóveis & móveis' },
  { value: 'AUTOMOTIVE', label: 'Automóveis' },
  { value: 'FOOD_GROCERY', label: 'Alimentação' },
  { value: 'HEALTH_BEAUTY', label: 'Saúde & beleza' },
  { value: 'OTHER', label: 'Outros' },
] as const;

export const MZ_PROVINCES: Array<{ name: string; districts: string[] }> = [
  {
    name: 'Maputo Cidade',
    districts: [
      'KaMpfumo',
      'Nlhamankulu',
      'KaMaxaquene',
      'KaMavota',
      'KaTembe',
      'KaNyaka',
    ],
  },
  {
    name: 'Maputo Província',
    districts: [
      'Boane',
      'Magude',
      'Manhiça',
      'Marracuene',
      'Matola',
      'Matutuíne',
      'Moamba',
      'Namaacha',
    ],
  },
  {
    name: 'Gaza',
    districts: [
      'Bilene',
      'Chibuto',
      'Chicualacuala',
      'Chigubo',
      'Chókwè',
      'Guijá',
      'Mabalane',
      'Manjacaze',
      'Massangena',
      'Massingir',
      'Xai-Xai',
    ],
  },
  {
    name: 'Inhambane',
    districts: [
      'Funhalouro',
      'Govuro',
      'Homoíne',
      'Inhambane',
      'Inharrime',
      'Inhassoro',
      'Jangamo',
      'Mabote',
      'Massinga',
      'Maxixe',
      'Morrumbene',
      'Panda',
      'Vilankulo',
      'Zavala',
    ],
  },
  {
    name: 'Sofala',
    districts: [
      'Beira',
      'Búzi',
      'Caia',
      'Chemba',
      'Cheringoma',
      'Chibabava',
      'Dondo',
      'Gorongosa',
      'Machanga',
      'Maringué',
      'Marromeu',
      'Muanza',
      'Nhamatanda',
    ],
  },
  {
    name: 'Manica',
    districts: [
      'Báruè',
      'Gondola',
      'Guro',
      'Macate',
      'Machaze',
      'Macossa',
      'Manica',
      'Mossurize',
      'Sussundenga',
      'Tambara',
      'Vanduzi',
      'Chimoio',
    ],
  },
  {
    name: 'Tete',
    districts: [
      'Angónia',
      'Cahora-Bassa',
      'Changara',
      'Chifunde',
      'Chiuta',
      'Doa',
      'Macanga',
      'Magoé',
      'Marara',
      'Marávia',
      'Moatize',
      'Mutarara',
      'Tsangano',
      'Zumbo',
      'Tete',
    ],
  },
  {
    name: 'Zambézia',
    districts: [
      'Alto Molócuè',
      'Chinde',
      'Derre',
      'Gilé',
      'Gurué',
      'Ile',
      'Inhassunge',
      'Lugela',
      'Maganja da Costa',
      'Milange',
      'Mocuba',
      'Mocubela',
      'Molumbo',
      'Mopeia',
      'Morrumbala',
      'Mulevala',
      'Namacurra',
      'Namarroi',
      'Nicoadala',
      'Pebane',
      'Quelimane',
    ],
  },
  {
    name: 'Nampula',
    districts: [
      'Angoche',
      'Eráti',
      'Ilha de Moçambique',
      'Lalaua',
      'Larde',
      'Liúpo',
      'Malema',
      'Meconta',
      'Mecubúri',
      'Memba',
      'Mogincual',
      'Mogovolas',
      'Moma',
      'Monapo',
      'Mossuril',
      'Muecate',
      'Murrupula',
      'Nacala-a-Velha',
      'Nacala Porto',
      'Nacarôa',
      'Nampula',
      'Rapale',
      'Ribáuè',
    ],
  },
  {
    name: 'Cabo Delgado',
    districts: [
      'Ancuabe',
      'Balama',
      'Chiúre',
      'Ibo',
      'Macomia',
      'Mecúfi',
      'Meluco',
      'Metuge',
      'Mocímboa da Praia',
      'Montepuez',
      'Mueda',
      'Muidumbe',
      'Namuno',
      'Nangade',
      'Palma',
      'Pemba',
      'Quissanga',
    ],
  },
  {
    name: 'Niassa',
    districts: [
      'Cuamba',
      'Lago',
      'Lichinga',
      'Majune',
      'Mandimba',
      'Marrupa',
      'Maúa',
      'Mavago',
      'Mecanhelas',
      'Mecula',
      'Metarica',
      'Muembe',
      "N'gauma",
      'Nipepe',
      'Sanga',
    ],
  },
];

export function isValidMzLocation(province: string, district: string) {
  const entry = MZ_PROVINCES.find((p) => p.name === province);
  return Boolean(entry?.districts.includes(district));
}
